/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;


public class AppTest {

    private static final long TIMEOUT = 3;

    @Test
    @Timeout(value = TIMEOUT)
    public void testArgOk() {
        String[] strings = {"ROUTE", "JAURES"};
        assertTrue(App.argsIsOk(strings));
    }

    @Test
    @Timeout(value = TIMEOUT)
    public void testArgOk1() {
        String[] strings = {"ROUTE"};
        assertTrue(App.argsIsOk(strings));
    }

    @Test
    @Timeout(value = TIMEOUT)
    public void testNotArgOk() {
        String[] strings = {"ROUTE", "JAURES", "PARIS", "MARSEILLE", "OURQ"};
        assertFalse(App.argsIsOk(strings));
    }

    @Test
    @Timeout(value = TIMEOUT)
    public void testNotArgOkNoArgument() {
        String[] strings = {};
        assertFalse(App.argsIsOk(strings));
    }

    @Test
    @Timeout(value = TIMEOUT)
    public void testHasCsvTimeFile() {
        String[] args = {"", ""};
        assertTrue(App.hasCsvTimeFile(args));
    }


}
