/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;


public class AppTest {

    private static final long TIMEOUT = 2;

    @Test
    @Timeout(value = TIMEOUT, unit = TimeUnit.SECONDS)
    public void testArgOk(){
        String[] strings = {"ROUTE", "JAURES", "PARIS"};
        assertTrue(App.argsIsOk(strings));
    }

    @Test
    @Timeout(value = TIMEOUT, unit = TimeUnit.SECONDS)
    public void testNotArgOk(){
        String[] strings = {"ROUTE", "JAURES", "PARIS", "MARSEILLE"};
        assertFalse(App.argsIsOk(strings));
    }

}
